In [19]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 
from sklearn.datasets import load_iris
from sklearn import tree
import matplotlib.pyplot as plt

In [6]:
# Loading data
irisData = load_iris()

In [8]:
X = irisData.data
y = irisData.target

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [10]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [12]:
y_pred = classifier.predict(X_test) 
y_pred

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 2, 0, 1, 0, 2, 0, 1, 0, 0, 2, 0, 2, 2,
       2, 1, 2, 2, 1, 0, 2, 2])

In [13]:
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
cm

Accuracy :  0.9666666666666667


array([[12,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 10]])

In [16]:
from sklearn.metrics import classification_report, confusion_matrix

In [17]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[12  0  0]
 [ 0  7  0]
 [ 0  1 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.88      1.00      0.93         7
           2       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [18]:
print(accuracy_score(y_test,y_pred)*100)

96.66666666666667
