In [1]:
import numpy as np 


In [2]:
x = np.array([1,2,3,4])

In [3]:
print(x)

[1 2 3 4]


In [4]:
print(type(x))

<class 'numpy.ndarray'>


In [5]:
print(x.shape)

(4,)


In [6]:
y = np.array([[1,2],[3,4]])

In [7]:
print(y)
print(y.shape)

[[1 2]
 [3 4]]
(2, 2)


In [8]:
z = np.array([[1+0.j,2+5.J]])

In [9]:
print(z)
print(z.shape)

[[1.+0.j 2.+5.j]]
(1, 2)


In [10]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
print(a.shape)

(2, 3)


In [12]:
b = np.ones((2,3),dtype=int)
print(b)

[[1 1 1]
 [1 1 1]]


In [13]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
e = np.arange(10)

In [15]:
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
e = np.arange(12,21)
print(e)

[12 13 14 15 16 17 18 19 20]


In [17]:
e= np.arange(5,20,3)
print(e)

[ 5  8 11 14 17]


In [19]:
f=np.linspace(1,20,7)
print(f)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [20]:
g=np.random.random((3,4))
print(g)

[[0.41108369 0.07042872 0.19893907 0.33828484]
 [0.29516947 0.94038304 0.83385649 0.71919587]
 [0.34410082 0.85419486 0.46727016 0.68424038]]


In [43]:
h = np.random.random((3,4))


In [42]:
print(h.reshape(2,3,3))

NameError: name 'q' is not defined

In [29]:
x = np.arange(12)
print(x)
print(x[4])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
4


In [30]:
print(x[-1])

11


In [31]:
x.resize(3,4)

In [32]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
print(x[2][3])

11


In [34]:
y = np.arange(1,26)
print(y)
print(y[:3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[1 2 3]


In [35]:
print(y[10:])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [37]:
print(y[10:21])

[11 12 13 14 15 16 17 18 19 20 21]


In [38]:
print(y[-5:])

[21 22 23 24 25]


In [39]:
print(y[3:-3])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [40]:
print(y[::3])

[ 1  4  7 10 13 16 19 22 25]


In [41]:
print(y.reshape((5,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [45]:
y = y.reshape((5,5))
print(y)
print(y[:5,:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [46]:
print(y[2:-1,1:-1])

[[12 13 14]
 [17 18 19]]


In [47]:
print(y[:,:-1])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [48]:
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [49]:
print(y[1::2,1:2])

[[ 7]
 [17]]


In [50]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a+b)
print(a-b)
print(b-a)
print(a**2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[5 5 5 5 5]
[ 1  4  9 16 25]


In [51]:
print(a>3)

[False False False  True  True]


In [52]:
a = np.arange(0,4).reshape((2,2))

In [54]:
b = np.eye(2)

In [55]:
print(a*b)

[[0. 0.]
 [0. 3.]]


In [56]:
print(np.dot(a,b))

[[0. 1.]
 [2. 3.]]


In [57]:
x = np.arange(1,10).reshape(3,3)

In [58]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
print(x.sum())

45


In [61]:
print(x.sum(axis=0))

[12 15 18]


In [62]:
print(x.sum(axis=1))

[ 6 15 24]


In [63]:
x = np.arange(1,19).reshape(3,3,2)

In [64]:
print(x)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [65]:
x = np.arange(1,10).reshape(3,3)
print(x.max())

9


In [66]:
print(x.max(axis=0))

[7 8 9]


In [67]:
print(x.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
